// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxootumlyqvkvqjqyhfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4b290dW1seXF2a3ZxanF5aGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjgzMDAsImV4cCI6MjA2OTA0NDMwMH0.daMLL2pYFR0xN258zHIDYLapl-q5-DSqh6HXvPg9BcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});